# Generated by Django 4.1.7 on 2023-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_comment_content'),
        ('home_page', '0003_userprofile'),
    ]

    operations = [
    ]
