# Generated by Django 4.1.7 on 2023-04-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_answer_pub_date_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
