# Generated by Django 4.1.7 on 2023-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_alter_activity_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
